version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./todolist:/app/todolist  # 로컬 파일을 컨테이너에 마운트
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_HOST=mysql
      - DB_NAME=todolist_db
      - DB_USER=root
      - DB_PASSWORD=1234
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todolist_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
